[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["Denis Aminov <Denisaminov74@gmail.com>"]
packages = [
  { include = "brain_games" },
]

[tool.poetry.dependencies]
python = "^3.8"
<<<<<<< HEAD
prompt = "^0.4.1"
=======
>>>>>>> 3f4be694ac4830836c6cbcbb6fceac197270a109

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
